experiment_name: modelnet40_noise
data_path: &data_path data/modelnet40_ply_hdf5_2048
epoch: &epoch 300
seed: 3407

dataloader:
  num_workers: &num_workers 4
  train_loader:
    num_workers: *num_workers
    batch_size: 8
  val_loader:
    num_workers: *num_workers
    batch_size: 1
  test_loader:
    num_workers: *num_workers
    batch_size: 1

dataset:
  name: &dataset_name ModelNet40Reg
  model: &mode crop
  normal: &use_normal False
  train_set:
    name: *dataset_name
    data_path: *data_path
    train: True
    mode: *mode
    normal: *use_normal
    categories: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  val_set:
    name: *dataset_name
    data_path: *data_path
    train: False
    mode: *mode
    normal: *use_normal
    categories: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  test_set:
    name: *dataset_name
    data_path: *data_path
    train: False
    mode: *mode
    normal: *use_normal
    categories: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]

overlap_pretrain_ckpt: ckpt/modelnet40_overlap_noise.py
model:
  name: DBDNet
  in_channel: 3
  base_channel: 32
  overlap_channel: 64
  layer_num: 6
  overlap_layer_num: 4
  train_iteration: &iteration 1
  test_iteration: 1
  keep_ratio: 1.0
  share_weights: True

loss:
  name: HybridLoss
  loss_args:
    correspondence_distance_cfg:
      weight: 10.0
      name: Iterative_Distance_Loss
      iteration: *iteration
    regression_R_cfg:
      weight: 1.0
      name: Rotation_Regression_Loss
      p: 1
      mode: cycle
    regression_t_cfg:
      weight: 1.0
      name: Translation_Regression_Loss
      p: 2
    distribution_cfg:
      weight: 1.0
      name: Regression_Distance_Loss

optimizer:
  name: AdamW
  lr: 1.0e-4
  weight_decay: 1.0e-4
  
lr_scheduler:
  name: Cosine_Schedule_With_Warmup
  num_warmup_steps: 5
  num_training_steps: *epoch

interval: 1
train_vis_labels:
  - 29
train_vis_ids:
  - 69